server:
    port: 5000
spring:
  application:
    name: eauction-products
  datasource:
    url: jdbc:postgresql://awseb-e-8pjhujz4gi-stack-awsebrdsdatabase-lugavxeivqrx.cte6oixnspqq.us-east-2.rds.amazonaws.com:5432/postgres
    username: pg00000
    password: pgangadharan
  cloud:
    config:
      enabled: false   
eureka:
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: false