server:
    port: 8083
spring:
  application:
    name: eauction-products
  data:
    mongodb:
      database: eauction
      uri: mongodb://localhost:27017
  cloud:
    config:
      enabled: false   
eureka:
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: false